language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gfortran

env:
  - FC=gfortran

before_script:
  - git clone --depth 1 https://github.com/mfem/mfem.git
  - make -C mfem -j2 serial MFEM_CXXFLAGS=-O
  - export MFEM_DIR=$PWD/mfem

script:
  - make -j2
  - make -j2 prove-all PROVE_OPTS=-v

cache:
  - ccache
