language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install gfortran

env:
  - FC=gfortran

before_script:
  - git clone https://github.com/mfem/mfem.git
  - cd mfem
  - make serial
  - export MFEM_DIR=$PWD
  - cd ..

script:
  - make -j2
  - make -j2 prove-mfem PROVE_OPTS=-v

